### ISSUE TITLE
Docs need an update to reflect usage of Quack

### ISSUE THREAD

**Issue by jistr** [PistonDevelopers/sdl2_window#121]
The usage docs are outdated, specifically the `let (w, h) = window.get_size();` line:

https://github.com/PistonDevelopers/sdl2_window/blob/4d453717532276ce5d3f6b63b732f5717f2bc4e6/README.md#how-to-set-up-gfx

I've been trying to get a window's size, but so far haven't been able to do so now that the sdl2_window library uses quack library. Too much rust magic for my current level of knowledge :) This is the furthest i got:

```
error: the trait `quack::GetFrom` is not implemented for the type `sdl2_window::Sdl2Window`
      let Size([w, h]) = GetFrom::get_from(Me::<Sdl2Window>, window);
```

**Comment by bvssvni** [comment]
The `GetFrom` trait is supposed to lift the `Get` trait.

```Rust
use quack::Get;

let Size([w, h]) = window.get();
```

**Comment by jistr** [comment]
Worked, thanks! Pull request incoming.
