### ISSUE TITLE
Incompatible with the new rust-sdl2 event API changes.

### ISSUE THREAD

**Issue by thebreadcat** [PistonDevelopers/sdl2_window#135]
A [new update to the rust-sdl2 event API](https://github.com/AngryLawyer/rust-sdl2/pull/344) has broken all sdl2 project, including this one. 

I might fix it myself later, but I'm putting up an issue for now.

**Comment by AngryLawyer** [comment]
Yeah, sorry about that :(

**Comment by thebreadcat** [comment]
Should we be returning a possible SDL error ( breaking even more things ) or just `unwrap()` the result from `sdl2::sdl::init()`?

**Comment by bvssvni** [comment]
Just use `unwrap` for now, until how to do fallbacks is cleared https://github.com/PistonDevelopers/window/issues/37
