### ISSUE TITLE
Events are being dropped

### ISSUE THREAD

**Issue by AerialX** [PistonDevelopers/sdl2_window#141]
Arch Linux x86_64 system here. Since the recent change to the sdl2 events, events aren't being queue'd up anymore, and timing issues will cause various events to be dropped.

As an example:

    for e in event::events(window) {
        match e { Event::Input(e) => println!("{:?}", e), _ => () }
    }

Moving the mouse while pressing keys will result in tons of mismatched key events where a press, release, or both just won't get handled. This becomes really obvious when clicking the mouse: if it's not completely stationary, the press or release will usually just disappear into the void.

**Comment by bvssvni** [comment]
One solution could be to call the low level API directly https://github.com/AngryLawyer/rust-sdl2/blob/b94b9cb5f55f835e214a158be46da92ed97ba9ff/src/sdl2/event.rs#L860-L866
