### ISSUE TITLE
PistonDevelopers/window was refactored breaking all imports

### ISSUE THREAD

**Issue by samuelleeuwenburg** [PistonDevelopers/sdl2_window#155]
Changes can be found here, https://github.com/PistonDevelopers/window/commit/3a69c417735157e3617e33a18b51c82e723a72f9

I'm not sure how to refactor this myself  since it is not just the naming that has changed but also the working as far as I can tell.

**Comment by bvssvni** [comment]
https://github.com/pistondevelopers/glutin_window is updated, can use it for reference.

**Comment by samuelleeuwenburg** [comment]
@bvssvni thats great, ill look into it!

**Comment by samuelleeuwenburg** [comment]
@bvssvni I am looking at it, but I'm afraid I lack the experience with rust to be able to refactor it.

**Comment by bvssvni** [comment]
@samuelleeuwenburg OK.
