### ISSUE TITLE
Push to crates.io

### ISSUE THREAD

**Issue by bombless** [PistonDevelopers/sdl2_window#161]
The build is broken now because it depends on shader_version ^0.0.5 semver.
I guess it's time for us to use 0.1.x semver for most projects.
Besides, "^" on 0.0.x will not work anyway.

**Comment by bombless** [comment]
(Maybe off-topic) piston2d-opengl_graphics on crates.io also needs update.

**Comment by bombless** [comment]
Now I see, modules of piston seems only work for github version.
So pushing to crates.io is never a must-do, am I right?

I'll close this issue tomorrow, but I do suggest we keep a version on crates.io that Beta users can use.
I'll check the dependency tree to see if that's possible.

**Comment by bvssvni** [comment]
The way we do it is to comment the version and follow the steps here when publishing https://github.com/PistonDevelopers/piston/issues/773

**Comment by bvssvni** [comment]
crates.io doesn't get updated for each PR, this must be done from time to time.
