### ISSUE TITLE
Typo in Documentation for `Sdl2Window` Struct

### ISSUE THREAD

**Issue by indiv0** [PistonDevelopers/sdl2_window#225]
`widow` instead of `window` on [this](https://github.com/PistonDevelopers/sdl2_window/blob/a8e56bb6062b8c77e7c8633967850484157e1ce1/src/lib.rs#L48) line.

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/sdl2_window/pull/226
