### ISSUE TITLE
The "How to Create a Window" sample fails

### ISSUE THREAD

**Issue by thoughton** [PistonDevelopers/sdl2_window#228]
Hi,

I might be missing something glaringly obvious, but I can't seem to get the embarrassingly simple "How to Create a Window" sample code in the readme to build.

The issue seems to be that Sdl2Window::new() no longer takes 2 parameters - it now apparently only takes 1.

I've tried modifying the sample based on what the definition of Sdl2Window::new() now looks like, but I'm a Rust beginner and I'm unable to wrangle an "opengl" parameter into the correct form...

Please could this sample be updated?  (Or am I likely doing something wrong?)

Thanks!

**Comment by mattico** [comment]
Hi thoughton.

It looks like the readme has gotten a bit out of date, I'm going to update the readme example and add some more examples of how to build a window.

**Comment by mattico** [comment]
It's also worth noting that if you want to actually use the window for anything, you'll need `piston` as that's the only way to actually get events out of the thing. I should probably add another example for that.

**Comment by mattico** [comment]
@thoughton Let me know if the new readme and examples answer your question. If they don't we can reopen this issue and figure it out.

**Comment by thoughton** [comment]
@mattico That works a lot better, thank you!

I did also have to add "piston" to the dependencies of course, and also 'extern' and 'use' the relevant crates, but maybe including that would be too detailed for a simple example in the readme...?

Thanks for the very quick reply!

**Comment by thoughton** [comment]
@mattico For what it's worth (very little!), here's the very simple sample I've put together using the snippet of code you provided, along with a few modifications I cobbled together by searching on libraries.io:

https://github.com/thoughton/piston_sdl2_window_test

Thanks again for your help!
